@startuml PlayerLogic
state "PlayerLogic State" as Cs001_PlayerLogic_State {
  state "Dead" as Cs001_PlayerLogic_State_Dead
  state "Alive" as Cs001_PlayerLogic_State_Alive
  state "Disabled" as Cs001_PlayerLogic_State_Disabled
}
Cs001_PlayerLogic_State_Disabled : OnEnter → Idle

[*] --> Cs001_PlayerLogic_State_Disabled
@enduml